// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SndrFs.proto

package com.sndr.proto;

public final class SndrFs {
  private SndrFs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SndrFSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sndr.proto.SndrFS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
     */
    com.sndr.proto.SndrFs.SndrFS.DataType getType();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    java.util.List<com.sndr.proto.SndrFs.SndrFS> 
        getNodeList();
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    com.sndr.proto.SndrFs.SndrFS getNode(int index);
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    int getNodeCount();
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    java.util.List<? extends com.sndr.proto.SndrFs.SndrFSOrBuilder> 
        getNodeOrBuilderList();
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    com.sndr.proto.SndrFs.SndrFSOrBuilder getNodeOrBuilder(
        int index);

    /**
     * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
     */
    boolean hasMetaData();
    /**
     * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
     */
    com.sndr.proto.SndrFs.MetaData getMetaData();
    /**
     * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
     */
    com.sndr.proto.SndrFs.MetaDataOrBuilder getMetaDataOrBuilder();
  }
  /**
   * Protobuf type {@code com.sndr.proto.SndrFS}
   */
  public  static final class SndrFS extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sndr.proto.SndrFS)
      SndrFSOrBuilder {
    // Use SndrFS.newBuilder() to construct.
    private SndrFS(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SndrFS() {
      type_ = 0;
      name_ = "";
      node_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SndrFS(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                node_ = new java.util.ArrayList<com.sndr.proto.SndrFs.SndrFS>();
                mutable_bitField0_ |= 0x00000004;
              }
              node_.add(
                  input.readMessage(com.sndr.proto.SndrFs.SndrFS.parser(), extensionRegistry));
              break;
            }
            case 34: {
              com.sndr.proto.SndrFs.MetaData.Builder subBuilder = null;
              if (metaData_ != null) {
                subBuilder = metaData_.toBuilder();
              }
              metaData_ = input.readMessage(com.sndr.proto.SndrFs.MetaData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(metaData_);
                metaData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          node_ = java.util.Collections.unmodifiableList(node_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_SndrFS_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_SndrFS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sndr.proto.SndrFs.SndrFS.class, com.sndr.proto.SndrFs.SndrFS.Builder.class);
    }

    /**
     * Protobuf enum {@code com.sndr.proto.SndrFS.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Raw = 0;</code>
       */
      Raw(0),
      /**
       * <code>Directory = 1;</code>
       */
      Directory(1),
      /**
       * <code>File = 2;</code>
       */
      File(2),
      /**
       * <code>Metadata = 3;</code>
       */
      Metadata(3),
      /**
       * <code>Symlink = 4;</code>
       */
      Symlink(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Raw = 0;</code>
       */
      public static final int Raw_VALUE = 0;
      /**
       * <code>Directory = 1;</code>
       */
      public static final int Directory_VALUE = 1;
      /**
       * <code>File = 2;</code>
       */
      public static final int File_VALUE = 2;
      /**
       * <code>Metadata = 3;</code>
       */
      public static final int Metadata_VALUE = 3;
      /**
       * <code>Symlink = 4;</code>
       */
      public static final int Symlink_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return Raw;
          case 1: return Directory;
          case 2: return File;
          case 3: return Metadata;
          case 4: return Symlink;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.sndr.proto.SndrFs.SndrFS.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.sndr.proto.SndrFS.DataType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
     */
    public com.sndr.proto.SndrFs.SndrFS.DataType getType() {
      com.sndr.proto.SndrFs.SndrFS.DataType result = com.sndr.proto.SndrFs.SndrFS.DataType.valueOf(type_);
      return result == null ? com.sndr.proto.SndrFs.SndrFS.DataType.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_FIELD_NUMBER = 3;
    private java.util.List<com.sndr.proto.SndrFs.SndrFS> node_;
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    public java.util.List<com.sndr.proto.SndrFs.SndrFS> getNodeList() {
      return node_;
    }
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    public java.util.List<? extends com.sndr.proto.SndrFs.SndrFSOrBuilder> 
        getNodeOrBuilderList() {
      return node_;
    }
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    public int getNodeCount() {
      return node_.size();
    }
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    public com.sndr.proto.SndrFs.SndrFS getNode(int index) {
      return node_.get(index);
    }
    /**
     * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
     */
    public com.sndr.proto.SndrFs.SndrFSOrBuilder getNodeOrBuilder(
        int index) {
      return node_.get(index);
    }

    public static final int METADATA_FIELD_NUMBER = 4;
    private com.sndr.proto.SndrFs.MetaData metaData_;
    /**
     * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
     */
    public boolean hasMetaData() {
      return metaData_ != null;
    }
    /**
     * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
     */
    public com.sndr.proto.SndrFs.MetaData getMetaData() {
      return metaData_ == null ? com.sndr.proto.SndrFs.MetaData.getDefaultInstance() : metaData_;
    }
    /**
     * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
     */
    public com.sndr.proto.SndrFs.MetaDataOrBuilder getMetaDataOrBuilder() {
      return getMetaData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.sndr.proto.SndrFs.SndrFS.DataType.Raw.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < node_.size(); i++) {
        output.writeMessage(3, node_.get(i));
      }
      if (metaData_ != null) {
        output.writeMessage(4, getMetaData());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.sndr.proto.SndrFs.SndrFS.DataType.Raw.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < node_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, node_.get(i));
      }
      if (metaData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMetaData());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sndr.proto.SndrFs.SndrFS)) {
        return super.equals(obj);
      }
      com.sndr.proto.SndrFs.SndrFS other = (com.sndr.proto.SndrFs.SndrFS) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getName()
          .equals(other.getName());
      result = result && getNodeList()
          .equals(other.getNodeList());
      result = result && (hasMetaData() == other.hasMetaData());
      if (hasMetaData()) {
        result = result && getMetaData()
            .equals(other.getMetaData());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getNodeCount() > 0) {
        hash = (37 * hash) + NODE_FIELD_NUMBER;
        hash = (53 * hash) + getNodeList().hashCode();
      }
      if (hasMetaData()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetaData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sndr.proto.SndrFs.SndrFS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sndr.proto.SndrFs.SndrFS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sndr.proto.SndrFs.SndrFS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sndr.proto.SndrFS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sndr.proto.SndrFS)
        com.sndr.proto.SndrFs.SndrFSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_SndrFS_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_SndrFS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sndr.proto.SndrFs.SndrFS.class, com.sndr.proto.SndrFs.SndrFS.Builder.class);
      }

      // Construct using com.sndr.proto.SndrFs.SndrFS.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        name_ = "";

        if (nodeBuilder_ == null) {
          node_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          nodeBuilder_.clear();
        }
        if (metaDataBuilder_ == null) {
          metaData_ = null;
        } else {
          metaData_ = null;
          metaDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_SndrFS_descriptor;
      }

      public com.sndr.proto.SndrFs.SndrFS getDefaultInstanceForType() {
        return com.sndr.proto.SndrFs.SndrFS.getDefaultInstance();
      }

      public com.sndr.proto.SndrFs.SndrFS build() {
        com.sndr.proto.SndrFs.SndrFS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sndr.proto.SndrFs.SndrFS buildPartial() {
        com.sndr.proto.SndrFs.SndrFS result = new com.sndr.proto.SndrFs.SndrFS(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.type_ = type_;
        result.name_ = name_;
        if (nodeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            node_ = java.util.Collections.unmodifiableList(node_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.node_ = node_;
        } else {
          result.node_ = nodeBuilder_.build();
        }
        if (metaDataBuilder_ == null) {
          result.metaData_ = metaData_;
        } else {
          result.metaData_ = metaDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sndr.proto.SndrFs.SndrFS) {
          return mergeFrom((com.sndr.proto.SndrFs.SndrFS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sndr.proto.SndrFs.SndrFS other) {
        if (other == com.sndr.proto.SndrFs.SndrFS.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (nodeBuilder_ == null) {
          if (!other.node_.isEmpty()) {
            if (node_.isEmpty()) {
              node_ = other.node_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureNodeIsMutable();
              node_.addAll(other.node_);
            }
            onChanged();
          }
        } else {
          if (!other.node_.isEmpty()) {
            if (nodeBuilder_.isEmpty()) {
              nodeBuilder_.dispose();
              nodeBuilder_ = null;
              node_ = other.node_;
              bitField0_ = (bitField0_ & ~0x00000004);
              nodeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodeFieldBuilder() : null;
            } else {
              nodeBuilder_.addAllMessages(other.node_);
            }
          }
        }
        if (other.hasMetaData()) {
          mergeMetaData(other.getMetaData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sndr.proto.SndrFs.SndrFS parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sndr.proto.SndrFs.SndrFS) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
       */
      public com.sndr.proto.SndrFs.SndrFS.DataType getType() {
        com.sndr.proto.SndrFs.SndrFS.DataType result = com.sndr.proto.SndrFs.SndrFS.DataType.valueOf(type_);
        return result == null ? com.sndr.proto.SndrFs.SndrFS.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
       */
      public Builder setType(com.sndr.proto.SndrFs.SndrFS.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.sndr.proto.SndrFS.DataType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.sndr.proto.SndrFs.SndrFS> node_ =
        java.util.Collections.emptyList();
      private void ensureNodeIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          node_ = new java.util.ArrayList<com.sndr.proto.SndrFs.SndrFS>(node_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sndr.proto.SndrFs.SndrFS, com.sndr.proto.SndrFs.SndrFS.Builder, com.sndr.proto.SndrFs.SndrFSOrBuilder> nodeBuilder_;

      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public java.util.List<com.sndr.proto.SndrFs.SndrFS> getNodeList() {
        if (nodeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(node_);
        } else {
          return nodeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public int getNodeCount() {
        if (nodeBuilder_ == null) {
          return node_.size();
        } else {
          return nodeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public com.sndr.proto.SndrFs.SndrFS getNode(int index) {
        if (nodeBuilder_ == null) {
          return node_.get(index);
        } else {
          return nodeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder setNode(
          int index, com.sndr.proto.SndrFs.SndrFS value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeIsMutable();
          node_.set(index, value);
          onChanged();
        } else {
          nodeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder setNode(
          int index, com.sndr.proto.SndrFs.SndrFS.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder addNode(com.sndr.proto.SndrFs.SndrFS value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeIsMutable();
          node_.add(value);
          onChanged();
        } else {
          nodeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder addNode(
          int index, com.sndr.proto.SndrFs.SndrFS value) {
        if (nodeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodeIsMutable();
          node_.add(index, value);
          onChanged();
        } else {
          nodeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder addNode(
          com.sndr.proto.SndrFs.SndrFS.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.add(builderForValue.build());
          onChanged();
        } else {
          nodeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder addNode(
          int index, com.sndr.proto.SndrFs.SndrFS.Builder builderForValue) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder addAllNode(
          java.lang.Iterable<? extends com.sndr.proto.SndrFs.SndrFS> values) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, node_);
          onChanged();
        } else {
          nodeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder clearNode() {
        if (nodeBuilder_ == null) {
          node_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          nodeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public Builder removeNode(int index) {
        if (nodeBuilder_ == null) {
          ensureNodeIsMutable();
          node_.remove(index);
          onChanged();
        } else {
          nodeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public com.sndr.proto.SndrFs.SndrFS.Builder getNodeBuilder(
          int index) {
        return getNodeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public com.sndr.proto.SndrFs.SndrFSOrBuilder getNodeOrBuilder(
          int index) {
        if (nodeBuilder_ == null) {
          return node_.get(index);  } else {
          return nodeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public java.util.List<? extends com.sndr.proto.SndrFs.SndrFSOrBuilder> 
           getNodeOrBuilderList() {
        if (nodeBuilder_ != null) {
          return nodeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(node_);
        }
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public com.sndr.proto.SndrFs.SndrFS.Builder addNodeBuilder() {
        return getNodeFieldBuilder().addBuilder(
            com.sndr.proto.SndrFs.SndrFS.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public com.sndr.proto.SndrFs.SndrFS.Builder addNodeBuilder(
          int index) {
        return getNodeFieldBuilder().addBuilder(
            index, com.sndr.proto.SndrFs.SndrFS.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sndr.proto.SndrFS node = 3;</code>
       */
      public java.util.List<com.sndr.proto.SndrFs.SndrFS.Builder> 
           getNodeBuilderList() {
        return getNodeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.sndr.proto.SndrFs.SndrFS, com.sndr.proto.SndrFs.SndrFS.Builder, com.sndr.proto.SndrFs.SndrFSOrBuilder> 
          getNodeFieldBuilder() {
        if (nodeBuilder_ == null) {
          nodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.sndr.proto.SndrFs.SndrFS, com.sndr.proto.SndrFs.SndrFS.Builder, com.sndr.proto.SndrFs.SndrFSOrBuilder>(
                  node_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          node_ = null;
        }
        return nodeBuilder_;
      }

      private com.sndr.proto.SndrFs.MetaData metaData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sndr.proto.SndrFs.MetaData, com.sndr.proto.SndrFs.MetaData.Builder, com.sndr.proto.SndrFs.MetaDataOrBuilder> metaDataBuilder_;
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public boolean hasMetaData() {
        return metaDataBuilder_ != null || metaData_ != null;
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public com.sndr.proto.SndrFs.MetaData getMetaData() {
        if (metaDataBuilder_ == null) {
          return metaData_ == null ? com.sndr.proto.SndrFs.MetaData.getDefaultInstance() : metaData_;
        } else {
          return metaDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public Builder setMetaData(com.sndr.proto.SndrFs.MetaData value) {
        if (metaDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metaData_ = value;
          onChanged();
        } else {
          metaDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public Builder setMetaData(
          com.sndr.proto.SndrFs.MetaData.Builder builderForValue) {
        if (metaDataBuilder_ == null) {
          metaData_ = builderForValue.build();
          onChanged();
        } else {
          metaDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public Builder mergeMetaData(com.sndr.proto.SndrFs.MetaData value) {
        if (metaDataBuilder_ == null) {
          if (metaData_ != null) {
            metaData_ =
              com.sndr.proto.SndrFs.MetaData.newBuilder(metaData_).mergeFrom(value).buildPartial();
          } else {
            metaData_ = value;
          }
          onChanged();
        } else {
          metaDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public Builder clearMetaData() {
        if (metaDataBuilder_ == null) {
          metaData_ = null;
          onChanged();
        } else {
          metaData_ = null;
          metaDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public com.sndr.proto.SndrFs.MetaData.Builder getMetaDataBuilder() {
        
        onChanged();
        return getMetaDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      public com.sndr.proto.SndrFs.MetaDataOrBuilder getMetaDataOrBuilder() {
        if (metaDataBuilder_ != null) {
          return metaDataBuilder_.getMessageOrBuilder();
        } else {
          return metaData_ == null ?
              com.sndr.proto.SndrFs.MetaData.getDefaultInstance() : metaData_;
        }
      }
      /**
       * <code>optional .com.sndr.proto.MetaData metaData = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sndr.proto.SndrFs.MetaData, com.sndr.proto.SndrFs.MetaData.Builder, com.sndr.proto.SndrFs.MetaDataOrBuilder> 
          getMetaDataFieldBuilder() {
        if (metaDataBuilder_ == null) {
          metaDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sndr.proto.SndrFs.MetaData, com.sndr.proto.SndrFs.MetaData.Builder, com.sndr.proto.SndrFs.MetaDataOrBuilder>(
                  getMetaData(),
                  getParentForChildren(),
                  isClean());
          metaData_ = null;
        }
        return metaDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.sndr.proto.SndrFS)
    }

    // @@protoc_insertion_point(class_scope:com.sndr.proto.SndrFS)
    private static final com.sndr.proto.SndrFs.SndrFS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sndr.proto.SndrFs.SndrFS();
    }

    public static com.sndr.proto.SndrFs.SndrFS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SndrFS>
        PARSER = new com.google.protobuf.AbstractParser<SndrFS>() {
      public SndrFS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SndrFS(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SndrFS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SndrFS> getParserForType() {
      return PARSER;
    }

    public com.sndr.proto.SndrFs.SndrFS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sndr.proto.MetaData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 hash = 1;</code>
     */
    long getHash();

    /**
     * <code>optional uint64 size = 2;</code>
     */
    long getSize();

    /**
     * <code>optional .google.protobuf.Timestamp modified = 3;</code>
     */
    boolean hasModified();
    /**
     * <code>optional .google.protobuf.Timestamp modified = 3;</code>
     */
    com.google.protobuf.Timestamp getModified();
    /**
     * <code>optional .google.protobuf.Timestamp modified = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder();

    /**
     * <code>optional string mimetype = 4;</code>
     */
    java.lang.String getMimetype();
    /**
     * <code>optional string mimetype = 4;</code>
     */
    com.google.protobuf.ByteString
        getMimetypeBytes();
  }
  /**
   * Protobuf type {@code com.sndr.proto.MetaData}
   */
  public  static final class MetaData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sndr.proto.MetaData)
      MetaDataOrBuilder {
    // Use MetaData.newBuilder() to construct.
    private MetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetaData() {
      hash_ = 0L;
      size_ = 0L;
      mimetype_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MetaData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              hash_ = input.readUInt64();
              break;
            }
            case 16: {

              size_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (modified_ != null) {
                subBuilder = modified_.toBuilder();
              }
              modified_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(modified_);
                modified_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              mimetype_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_MetaData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_MetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sndr.proto.SndrFs.MetaData.class, com.sndr.proto.SndrFs.MetaData.Builder.class);
    }

    public static final int HASH_FIELD_NUMBER = 1;
    private long hash_;
    /**
     * <code>optional uint64 hash = 1;</code>
     */
    public long getHash() {
      return hash_;
    }

    public static final int SIZE_FIELD_NUMBER = 2;
    private long size_;
    /**
     * <code>optional uint64 size = 2;</code>
     */
    public long getSize() {
      return size_;
    }

    public static final int MODIFIED_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp modified_;
    /**
     * <code>optional .google.protobuf.Timestamp modified = 3;</code>
     */
    public boolean hasModified() {
      return modified_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp modified = 3;</code>
     */
    public com.google.protobuf.Timestamp getModified() {
      return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp modified = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
      return getModified();
    }

    public static final int MIMETYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object mimetype_;
    /**
     * <code>optional string mimetype = 4;</code>
     */
    public java.lang.String getMimetype() {
      java.lang.Object ref = mimetype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mimetype_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mimetype = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMimetypeBytes() {
      java.lang.Object ref = mimetype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimetype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hash_ != 0L) {
        output.writeUInt64(1, hash_);
      }
      if (size_ != 0L) {
        output.writeUInt64(2, size_);
      }
      if (modified_ != null) {
        output.writeMessage(3, getModified());
      }
      if (!getMimetypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mimetype_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hash_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, hash_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, size_);
      }
      if (modified_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getModified());
      }
      if (!getMimetypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mimetype_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sndr.proto.SndrFs.MetaData)) {
        return super.equals(obj);
      }
      com.sndr.proto.SndrFs.MetaData other = (com.sndr.proto.SndrFs.MetaData) obj;

      boolean result = true;
      result = result && (getHash()
          == other.getHash());
      result = result && (getSize()
          == other.getSize());
      result = result && (hasModified() == other.hasModified());
      if (hasModified()) {
        result = result && getModified()
            .equals(other.getModified());
      }
      result = result && getMimetype()
          .equals(other.getMimetype());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHash());
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      if (hasModified()) {
        hash = (37 * hash) + MODIFIED_FIELD_NUMBER;
        hash = (53 * hash) + getModified().hashCode();
      }
      hash = (37 * hash) + MIMETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMimetype().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sndr.proto.SndrFs.MetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.MetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sndr.proto.SndrFs.MetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sndr.proto.SndrFs.MetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sndr.proto.SndrFs.MetaData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sndr.proto.MetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sndr.proto.MetaData)
        com.sndr.proto.SndrFs.MetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_MetaData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_MetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sndr.proto.SndrFs.MetaData.class, com.sndr.proto.SndrFs.MetaData.Builder.class);
      }

      // Construct using com.sndr.proto.SndrFs.MetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        hash_ = 0L;

        size_ = 0L;

        if (modifiedBuilder_ == null) {
          modified_ = null;
        } else {
          modified_ = null;
          modifiedBuilder_ = null;
        }
        mimetype_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sndr.proto.SndrFs.internal_static_com_sndr_proto_MetaData_descriptor;
      }

      public com.sndr.proto.SndrFs.MetaData getDefaultInstanceForType() {
        return com.sndr.proto.SndrFs.MetaData.getDefaultInstance();
      }

      public com.sndr.proto.SndrFs.MetaData build() {
        com.sndr.proto.SndrFs.MetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.sndr.proto.SndrFs.MetaData buildPartial() {
        com.sndr.proto.SndrFs.MetaData result = new com.sndr.proto.SndrFs.MetaData(this);
        result.hash_ = hash_;
        result.size_ = size_;
        if (modifiedBuilder_ == null) {
          result.modified_ = modified_;
        } else {
          result.modified_ = modifiedBuilder_.build();
        }
        result.mimetype_ = mimetype_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sndr.proto.SndrFs.MetaData) {
          return mergeFrom((com.sndr.proto.SndrFs.MetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sndr.proto.SndrFs.MetaData other) {
        if (other == com.sndr.proto.SndrFs.MetaData.getDefaultInstance()) return this;
        if (other.getHash() != 0L) {
          setHash(other.getHash());
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (other.hasModified()) {
          mergeModified(other.getModified());
        }
        if (!other.getMimetype().isEmpty()) {
          mimetype_ = other.mimetype_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sndr.proto.SndrFs.MetaData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sndr.proto.SndrFs.MetaData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long hash_ ;
      /**
       * <code>optional uint64 hash = 1;</code>
       */
      public long getHash() {
        return hash_;
      }
      /**
       * <code>optional uint64 hash = 1;</code>
       */
      public Builder setHash(long value) {
        
        hash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 hash = 1;</code>
       */
      public Builder clearHash() {
        
        hash_ = 0L;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>optional uint64 size = 2;</code>
       */
      public long getSize() {
        return size_;
      }
      /**
       * <code>optional uint64 size = 2;</code>
       */
      public Builder setSize(long value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 size = 2;</code>
       */
      public Builder clearSize() {
        
        size_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp modified_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> modifiedBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public boolean hasModified() {
        return modifiedBuilder_ != null || modified_ != null;
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public com.google.protobuf.Timestamp getModified() {
        if (modifiedBuilder_ == null) {
          return modified_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
        } else {
          return modifiedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public Builder setModified(com.google.protobuf.Timestamp value) {
        if (modifiedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          modified_ = value;
          onChanged();
        } else {
          modifiedBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public Builder setModified(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (modifiedBuilder_ == null) {
          modified_ = builderForValue.build();
          onChanged();
        } else {
          modifiedBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public Builder mergeModified(com.google.protobuf.Timestamp value) {
        if (modifiedBuilder_ == null) {
          if (modified_ != null) {
            modified_ =
              com.google.protobuf.Timestamp.newBuilder(modified_).mergeFrom(value).buildPartial();
          } else {
            modified_ = value;
          }
          onChanged();
        } else {
          modifiedBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public Builder clearModified() {
        if (modifiedBuilder_ == null) {
          modified_ = null;
          onChanged();
        } else {
          modified_ = null;
          modifiedBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getModifiedBuilder() {
        
        onChanged();
        return getModifiedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getModifiedOrBuilder() {
        if (modifiedBuilder_ != null) {
          return modifiedBuilder_.getMessageOrBuilder();
        } else {
          return modified_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : modified_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp modified = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getModifiedFieldBuilder() {
        if (modifiedBuilder_ == null) {
          modifiedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getModified(),
                  getParentForChildren(),
                  isClean());
          modified_ = null;
        }
        return modifiedBuilder_;
      }

      private java.lang.Object mimetype_ = "";
      /**
       * <code>optional string mimetype = 4;</code>
       */
      public java.lang.String getMimetype() {
        java.lang.Object ref = mimetype_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mimetype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mimetype = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMimetypeBytes() {
        java.lang.Object ref = mimetype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mimetype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mimetype = 4;</code>
       */
      public Builder setMimetype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mimetype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mimetype = 4;</code>
       */
      public Builder clearMimetype() {
        
        mimetype_ = getDefaultInstance().getMimetype();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mimetype = 4;</code>
       */
      public Builder setMimetypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mimetype_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.sndr.proto.MetaData)
    }

    // @@protoc_insertion_point(class_scope:com.sndr.proto.MetaData)
    private static final com.sndr.proto.SndrFs.MetaData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sndr.proto.SndrFs.MetaData();
    }

    public static com.sndr.proto.SndrFs.MetaData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MetaData>
        PARSER = new com.google.protobuf.AbstractParser<MetaData>() {
      public MetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetaData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetaData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetaData> getParserForType() {
      return PARSER;
    }

    public com.sndr.proto.SndrFs.MetaData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sndr_proto_SndrFS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sndr_proto_SndrFS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sndr_proto_MetaData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sndr_proto_MetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014SndrFs.proto\022\016com.sndr.proto\032\037google/p" +
      "rotobuf/timestamp.proto\"\340\001\n\006SndrFS\022-\n\004ty" +
      "pe\030\001 \001(\0162\037.com.sndr.proto.SndrFS.DataTyp" +
      "e\022\014\n\004name\030\002 \001(\t\022$\n\004node\030\003 \003(\0132\026.com.sndr" +
      ".proto.SndrFS\022*\n\010metaData\030\004 \001(\0132\030.com.sn" +
      "dr.proto.MetaData\"G\n\010DataType\022\007\n\003Raw\020\000\022\r" +
      "\n\tDirectory\020\001\022\010\n\004File\020\002\022\014\n\010Metadata\020\003\022\013\n" +
      "\007Symlink\020\004\"f\n\010MetaData\022\014\n\004hash\030\001 \001(\004\022\014\n\004" +
      "size\030\002 \001(\004\022,\n\010modified\030\003 \001(\0132\032.google.pr" +
      "otobuf.Timestamp\022\020\n\010mimetype\030\004 \001(\tB\002H\001b\006",
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_sndr_proto_SndrFS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sndr_proto_SndrFS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sndr_proto_SndrFS_descriptor,
        new java.lang.String[] { "Type", "Name", "Node", "MetaData", });
    internal_static_com_sndr_proto_MetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sndr_proto_MetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sndr_proto_MetaData_descriptor,
        new java.lang.String[] { "Hash", "Size", "Modified", "Mimetype", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
